debug: false

logging:
  caller: true
  trace_id: true
  stacktrace: error

server:
  network: "tcp"
  address: "0.0.0.0"
  port: 8080

observability:
  trace:
    exporter:
      type: "otlp-grpc"
      endpoint: "localhost:4317"
      timeout: 10s
      insecure: true
    batch_timeout: 5s
    max_batch_entries: 512
    export_timeout: 30s
    max_queue_size: 2048
    sampling_rate: 0.2
  metric:
    reader:
      type: prometheus
      listen: "0.0.0.0:9201"

cassandra:
  hosts:
    - "localhost:9042"
  username: ""
  password: ""
  keyspace: "gravatar"
