name: gravatar-with-qq-support

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  etcd-data:
  cassandra-data:

services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - redis-data:/data

  etcd:
    image: quay.io/coreos/etcd:v3.5.9-arm64
    entrypoint: /usr/local/bin/etcd
    command:
      - --name=etcd
      - --data-dir=/etcd_data
      - --initial-advertise-peer-urls=http://etcd:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=etcd=http://etcd:2380
      - --initial-cluster-state=new
      - --heartbeat-interval=250
      - --election-timeout=1250
      - --experimental-enable-distributed-tracing=true
      - --experimental-distributed-tracing-address='jaeger:4317'
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - app-network
    volumes:
      - etcd-data:/etcd_data

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - app-network

  cassandra:
    image: cassandra:4
    ports:
      - "9042:9042"
    networks:
      - app-network
    volumes:
      - cassandra-data:/var/lib/cassandra/data
