name: gravatar-with-qq-avatar

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  etcd-data:
  scylladb-data:

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - app-network

  scylladb:
    image: scylladb/scylla:5.4
    ports:
      - "9042:9042"
    networks:
      - app-network
    volumes:
      - scylladb-data:/var/lib/scylla
